<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SBSSData.Softball.Common\SBSSData.Softball.Common.csproj" />
    <ProjectReference Include="..\SBSSData.Softball.Stats\SBSSData.Softball.Stats.csproj" />
    <ProjectReference Include="..\SBSSData.Softball\SBSSData.Softball.csproj" />
  </ItemGroup>

</Project>
