<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SBSSData.Application.SyncDataStore\**" />
    <EmbeddedResource Remove="SBSSData.Application.SyncDataStore\**" />
    <None Remove="SBSSData.Application.SyncDataStore\**" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Dumpify" Version="0.6.5" />
    <PackageReference Include="LINQPad.Runtime" Version="8.3.7" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\SBSSData.Softball.Common\SBSSData.Softball.Common.csproj" />
    <ProjectReference Include="..\..\Libraries\SBSSData.Softball.Stats\SBSSData.Softball.Stats.csproj" />
    <ProjectReference Include="..\..\Libraries\SBSSData.Softball\SBSSData.Softball.csproj" />
  </ItemGroup>

</Project>
